# Generated by Django 3.1.1 on 2021-06-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkSeat_seat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subschedule',
            name='a1004',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1006',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1008',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1010',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1012',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1014',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1016',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1018',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1020',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1022',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1024',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1026',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1028',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1030',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1032',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1034',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1036',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1038',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1040',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1042',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1044',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1046',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1048',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1050',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1052',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1054',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1056',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1058',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1060',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1062',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1064',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1066',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1068',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1070',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1072',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1074',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1076',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1078',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1080',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1082',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1084',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1088',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1090',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1092',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1094',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1096',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1098',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1100',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1102',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1104',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1106',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1108',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1110',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1112',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1114',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1116',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1118',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1120',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1122',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1124',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1126',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1128',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1130',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1132',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1134',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1136',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1138',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1140',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1142',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1144',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1146',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1148',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1150',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1152',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1154',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1156',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1158',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1160',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1162',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1164',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1166',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1168',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1170',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1172',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1174',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1176',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1178',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1180',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1182',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1184',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1186',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1188',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1190',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1192',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1194',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1196',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1198',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1200',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1202',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1204',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1206',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1208',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1210',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1212',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1214',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1216',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1218',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1220',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1222',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1224',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1226',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1228',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1230',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1232',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1234',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1236',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1238',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1240',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subschedule',
            name='a1242',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
