# Generated by Django 3.1.1 on 2020-12-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PinkSeat_account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
